# Generated by Django 3.2.3 on 2021-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='First_name',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='Last_name',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(default='', editable=False, max_length=64),
        ),
    ]
