# Generated by Django 3.2.3 on 2021-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0002_auto_20210516_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=64)),
                ('Last_name', models.CharField(default='', max_length=64)),
                ('phone', models.BigIntegerField()),
                ('username', models.EmailField(default='', max_length=64)),
                ('password', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='First_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(default='', max_length=64),
        ),
    ]
