# Generated by Django 3.2.3 on 2021-05-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0004_auto_20210516_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
