# Generated by Django 3.2.3 on 2021-05-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0006_rename_password2_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('phone', models.BigIntegerField()),
                ('username', models.EmailField(default='', max_length=64)),
                ('password', models.CharField(default='', max_length=64)),
                ('password1', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='eventmanager',
            name='password1',
            field=models.CharField(default='', max_length=64),
        ),
    ]
