# Generated by Django 3.2.3 on 2021-05-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0007_auto_20210518_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmanager',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='eventmanager',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
