# Generated by Django 3.0.5 on 2021-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0011_auto_20210519_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maxpeople',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
